---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/color-modes"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/icons-font"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/parcel"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/react-nextjs"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/sass-js-esm"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/sass-js"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/starter"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/vite"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/vue"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/webpack"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
