---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/color-modes"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/icons-font"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/parcel"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/react-nextjs"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/sass-js-esm"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/sass-js"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/starter"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/vite"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/vue"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: "/packages/webpack"
    labels:
      - dependencies
    schedule:
      interval: monthly
    versioning-strategy: increase
